# Red Neuronal Multicapa

Una red neuronal multicapa tiene capas ocultas entre la entrada y la salida. A este tipo de red también se le conoce como perceptrón multicapa (MLP por sus siglas en inglés de multilayer perceptron)

En este ejercicio crearemos una red neuronal multicapa usando numpy.

INSTRUCCIONES: Completa el código faltante.

@juan1rving

In [2]:
# Importamos paquetes
import numpy as np

np.random.seed(42)

In [3]:
# Funciones necesarias
def sigmoid(x):
    """
    Función sigmoide
    """
    return 1/(1+np.exp(-x))

## Definamos la arquitectura de la red

<img src="files/test1.png">

In [4]:
# TODO: Especifica el tamaño de las capas de acuerdo al diagrama.
N_input = 4
N_hidden = 3
N_out = 2

## Definir los pesos

Recordemos que los pesos ahora los representamos con matrices y utilizaremos el producton de la siguiente forma:

$$
h = XW
$$

tal que,


$$W = \begin{bmatrix}
w_{1,1} & w_{1,2}
 \\
w_{2,1} & w_{2,2}
 \\
w_{3,1} & w_{3,2}
 \\
\end{bmatrix}$$

donde los renglones se relacionan con las entradas y las columnas con los nodos intermedios. Y las entradas son

$$ X = \begin{bmatrix} x_1 & x_2 & x_3 \end{bmatrix} $$

Como herramienta usaremos la fucnión normal. Verifica la documentación oficial de la función.

> numpy.random.normal(loc=0.0, scale=1.0, size=None)

TODO: construye a contrinuación matrices con valores aleatorios para la matriz de pesos entre la entrada y la oculta y para la oculta y la salida.

In [11]:
#TODO: Completa el código faltante

# Especifica la media y desviación estandar a usar.
mean = 0
stdev = 1

# crea las matrices de forma dinámica a partir de los valores que se pone en los tamaños de la red
W_input_to_hidden = np.random.normal(mean, stdev, (N_input, N_hidden))

W_hidden_out = np.random.normal(mean, stdev, (N_hidden, N_out))

X = np.random.normal(mean, stdev, (1, N_input))

print("pesos de la capa de entrada a la hidden\n", W_input_to_hidden)
print("pesos de la capa hidden a la salida\n", W_hidden_out)
print("inputs\n", X)

pesos de la capa de entrada a la hidden
 [[ 0.32408397 -0.38508228 -0.676922  ]
 [ 0.61167629  1.03099952  0.93128012]
 [-0.83921752 -0.30921238  0.33126343]
 [ 0.97554513 -0.47917424 -0.18565898]]
pesos de la capa hidden a la salida
 [[-1.10633497 -1.19620662]
 [ 0.81252582  1.35624003]
 [-0.07201012  1.0035329 ]]
inputs
 [[ 0.36163603 -0.64511975  0.36139561  1.53803657]]


## Calcular la salida

Recordemos de la lección que

$$ h = X W $$

$$ y = f(H) $$

In [12]:
# TODO: Producto punto
input_to_hidden = np.dot(X, W_input_to_hidden)
out_of_hidden = sigmoid(input_to_hidden)

print("salida de la capa oculta: ", out_of_hidden)

# TODO: Producto punto
input_to_out = np.dot(out_of_hidden, W_hidden_out) 
out_of_network = sigmoid(input_to_out)

print("salida de la red: ", out_of_network)


salida de la capa oculta:  [[0.7149872  0.16068863 0.2667021 ]]
salida de la red:  [[0.33633788 0.40861454]]


Como resultado debes de ver la salida de la red como un vector de dos elementos.
